project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Abdullahi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muhaksim
      - icon: twitter
        href: https://twitter.com/muhaksim
format:
  html:
    theme: flatly
    css: styles.css



