project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Abdullahi"
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muhaksim
      - icon: twitter
        href: https://twitter.com/muhaksim
    left: 
          - text: Posts
            file: index.qmd
          - tils/index.qmd
          - projects.qmd
  twitter-card:
    creator: "@muhaksim"
    site: "@muhaksim"

format:
  html:
    theme: flatly
    css: styles.css



